---
server:
    install: '1'
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: resin, ip: 192.168.2.146, memory: '512', sharedfolder: ~/workspace/resin, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /resin
    servername: resin.app
mysql:
    install: '1'
    root_password: root
    database: resin
    user: resin
    password: resin
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql, php5-gd]
xdebug:
    install: '1'
composer:
    install: '1'
app:
    key: mykeytest
