---
# application tasks to be customized and to run after the main provision

# - name: Install git
#  apt: name=git state=latest

#- name: Clone Resin
  # git: >
  #  repo=https://github.com/collectiveaccess/providence
  #  dest=/vagrant
  #  update=no

- name: Configure database.php
  template: src=env.tpl dest=/vagrant/.env

- name: Set permissions on storage/upload
  command: chmod +w /vagrant/storage

- name: Run artisan migrate
  shell: php /vagrant/artisan migrate --force
  sudo: yes
